name: Check Test
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Insert Empty key file
        run : |
          cd src/main/kotlin/com/easternkite/remain/ai
          echo package com.easternkite.remain.ai > key.kt
          echo const val KEY_GEMINI = \"ENTER YOUR KEY\" >> key.kt

      - name: Check Test
        run: ./gradlew test --no-configuration-cache